### PR TITLE
fdt: add support for set_property

### PR DESCRIPTION
**Pull request by sgonauer6wind**
This patch adds support to patch an existing property or
add a new one.

Signed-off-by: Stephane Gonauer <stephane.gonauer@6wind.com>

### CODE REVIEW

**Comment by molejar** [comment]
The `add_property` method is internally calling `self.props.append` but should call `self.append` instead. With your implementation can be added more properties with same name, what is not valid in FDT.
Please fix this method and also write tests for your code. Thanks

```python
    def add_property(self, name, data):
        if isinstance(data, int):
            prop = PropWords(name, data)
        elif isinstance(data, list):
            prop = PropWords(name, *data)
        elif isinstance(data, str):
            prop = PropStrings(name, data)
        else:
            raise Exception('data type not supported')
        self.append(prop)
````

Usage:

```python
    root_node = fdt.Node('/')
    root_node.add_property('int_prop', 1000)
    root_node.add_property('list_int_prop', [1, 2])
    root_node.add_property('str_prop', 'value')
```

**Comment by sgonauer6wind** [comment]
Hi, 

I updated the add_property property method as you requested. 
I'm not familiar with python and the its unit test framework so I need a bit more indication.

Would the attached patch ok for you ? 

diff --git a/tests/test_items_api.py b/tests/test_items_api.py
index 5756c8a..63bfe35 100644
--- a/tests/test_items_api.py
+++ b/tests/test_items_api.py
@@ -236,6 +236,42 @@ class NodeTestCase(unittest.TestCase):
         out += "};\n"
         self.assertEqual(str_data, out)
 
+DIRECTORY="tests/data/"
+class FFTTestCase(unittest.TestCase):
+
+    def setUp(self):
+        with open(DIRECTORY + "addresses.dts") as f:
+            data = f.read()
+            self.fdt = fdt.parse_dts(data)
+
+    def tearDown(self):
+        pass
+
+    def test_addprop(self):
+        # single word
+        self.fdt.set_property('d12', 12, '/simple-bus@1000000')
+        self.assertEqual(self.fdt.get_property('d12','/simple-bus@1000000').data[0], 12)
+        # string
+        self.fdt.set_property('string_prop', "test_str", '/simple-bus@1000000')
+        self.assertEqual(self.fdt.get_property('string_prop','/simple-bus@1000000').data[0], "test_str")
+        # word array
+        words = [1, 2, 3]
+        self.fdt.set_property('word_array', words, '/simple-bus@1000000')
+        self.assertEqual(self.fdt.get_property('word_array','/simple-bus@1000000').data, words)
+
+    def test_change_prop(self):
+        # single word
+        self.fdt.get_property('d12','/simple-bus@1000000')
+        self.fdt.set_property('d12', 20, '/simple-bus@1000000')
+        self.assertEqual(self.fdt.get_property('d12','/simple-bus@1000000').data[0], 20)
+        self.fdt.get_property('d12','/simple-bus@1000000')
+        # string
+        self.fdt.set_property('string_prop', "test_str2", '/simple-bus@1000000')
+        self.assertEqual(self.fdt.get_property('string_prop','/simple-bus@1000000').data[0], "test_str2")
+        # word array
+        words = [4, 5, 6]
+        self.fdt.set_property('word_array', words, '/simple-bus@1000000')
+        self.assertEqual(self.fdt.get_property('word_array','/simple-bus@1000000').data, words)

**Comment by sgonauer6wind** [comment]
I've added a dev branch to offer a test. 
Also implemented the change of API you requested.

Is the test ok for you ?

**Comment by molejar** [comment]
Sorry for other changes but individual `add_property` method has no sense if it functionality is covered by `set_property` method. Here is a new implementation of `set_property` without dependency on `add_property` and with full support of property types:

```python
    def set_property(self, name, value):
        if value is None:
            new_prop = Property(name)
        elif isinstance(value, int):
            new_prop = PropWords(name, value)
        elif isinstance(value, str):
            new_prop = PropStrings(name, value)
        elif isinstance(value, list) and isinstance(value[0], int):
            new_prop = PropWords(name, *value)
        elif isinstance(value, list) and isinstance(value[0], str):
            new_prop = PropStrings(name, *value)
        elif isinstance(value, (bytes, bytearray)):
            new_prop = PropBytes(name, data=value)
        else:
            raise TypeError('Value type not supported')
        new_prop.set_parent(self)
        old_prop = self.get_property(name)
        if old_prop is None:
            self.props.append(new_prop)
        else:
            index = self.props.index(old_prop)
            self.props[index] = new_prop
```
Please remove `add_property` method and add following test into `class NodeTestCase(unittest.TestCase):`

```python
    def test_set_property(self):
        root_node = fdt.Node('/')
        # add properties into node by set_property method
        root_node.set_property('prop', None)
        root_node.set_property('int_prop', 1000)
        root_node.set_property('list_int_prop', [1, 2])
        root_node.set_property('str_prop', 'value')
        root_node.set_property('list_str_prop', ['value1', 'value2'])
        root_node.set_property('bytes_prop', b'\x00\x55\x66')
        # validate types and values
        self.assertEqual(len(root_node.props), 6)
        self.assertIsInstance(root_node.get_property('prop'), fdt.Property)
        self.assertIsInstance(root_node.get_property('int_prop'), fdt.PropWords)
        self.assertEqual(root_node.get_property('int_prop').data, [1000])
        self.assertIsInstance(root_node.get_property('list_int_prop'), fdt.PropWords)
        self.assertEqual(root_node.get_property('list_int_prop').data, [1, 2])
        self.assertIsInstance(root_node.get_property('str_prop'), fdt.PropStrings)
        self.assertEqual(root_node.get_property('str_prop').data, ['value'])
        self.assertIsInstance(root_node.get_property('list_str_prop'), fdt.PropStrings)
        self.assertEqual(root_node.get_property('list_str_prop').data, ['value1', 'value2'])
        self.assertIsInstance(root_node.get_property('bytes_prop'), fdt.PropBytes)
        self.assertEqual(root_node.get_property('bytes_prop').data, b'\x00\x55\x66')
        # update property in node by set_property method
        root_node.set_property('list_int_prop', [1, 2, 3])
        # validate property value
        self.assertEqual(root_node.get_property('list_int_prop').data, [1, 2, 3])
```
Thanks

**Comment by sgonauer6wind** [comment]
Ok done per your request see other pull request

**Pull request closed without merging**
